/*!
 * Hasher <http://github.com/millermedeiros/Hasher>
 * Includes: millermedeiros.EventDispatcher (::evtDispatcher_version::), millermedeiros.queryUtils (::queryUtils_version::), millermedeiros.event-listenerFacade (::listenerFacade_version::)
 * @author Miller Medeiros <http://www.millermedeiros.com/>
 * @version ::version::
 * Released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
 */