/*!
 * Hasher <http://github.com/millermedeiros/Hasher>
 * Includes: js-signals (::js-signals_version::), millermedeiros.queryUtils (::queryUtils_version::), millermedeiros.event-listenerFacade (::listenerFacade_version::)
 * @author Miller Medeiros <http://www.millermedeiros.com/>
 * @version ::VERSION_NUMBER:: ::BUILD_DATE::
 * Released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
 */