/*!
 * Hasher
 * - History Manager for rich-media applications.
 * @author Miller Medeiros <http://www.millermedeiros.com/>
 * @version ::version::
 * Released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
 *
 * Includes: MM.EventDispatcher (::evtDispatcher_version::), MM.queryUtils (::queryUtils_version::)
 * @author Miller Medeiros <http://www.millermedeiros.com/>
 * Released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
 */